### ISSUE TITLE
Invalid Bookland region -> ISBN: 7798404510807

### ISSUE THREAD

**Issue by gusarg81** [JNRowe/pyisbn#22]
Hi,

I am developing and small app that reads books from a DB and validate each ISBN which maybe lack of ISBN-13 conversion (which is needed).

Now, the DB contains many ISBN like this one, which throws:

> pyisbn.validate("7798404510807")
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/gustavo/Nextcloud/GDNet/Clientes/Patalibro/Desarrollo Lector/GetBooksPrices/venv/lib/python3.10/site-packages/pyisbn/__init__.py", line 504, in validate
>     isbn = _isbn_cleanse(isbn)
>   File "/home/gustavo/Nextcloud/GDNet/Clientes/Patalibro/Desarrollo Lector/GetBooksPrices/venv/lib/python3.10/site-packages/pyisbn/__init__.py", line 414, in _isbn_cleanse
>     raise IsbnError('invalid Bookland region')
> pyisbn.IsbnError: invalid Bookland region

The Book indeed exist (https://www.quade.com.ar/agendas-2024/25415-agenda-2024-a5-2-dia-bruja-cristales-purpura-hechicera-7798404510807.html). Any ideas how to solve/skip this?

Environment Information
-----------------------

* OS: Ubuntu 22.04
* `pyisbn` version: 1.3.1
* `python` version: 3.10

**Comment by JNRowe** [comment]
Hi,

pyisbn only supports ISBNs.  It looks like you’ll want an EAN-13 parser to work with the example you’ve given, or any other item codes that aren’t from Bookland¹.

Thanks,

James

¹ https://en.m.wikipedia.org/wiki/Bookland
